---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - distance
        - dollar_cost_points_redeemed
        - flights_booked
        - flights_with_companions
        - loyalty_number
        - month
        - points_accumulated
        - points_redeemed
        - total_flights
        - year
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: AGGREGATION
          Policy:
            V1:
              Aggregation:
                AggregateColumns:
                  - Function: AVG
                    ColumnNames:
                    - points_accumulated
                    - points_redeemed
                  - Function: SUM
                    ColumnNames:
                    - points_accumulated
                    - points_redeemed
                  - Function: COUNT_DISTINCT
                    ColumnNames:
                    - loyalty_number
                DimensionColumns:
                  - distance
                  - dollar_cost_points_redeemed
                  - flights_booked
                  - flights_with_companions
                  - month
                  - total_flights
                  - year
                JoinColumns:
                  - loyalty_number
                JoinRequired: QUERY_RUNNER
                OutputConstraints:
                  - ColumnName: loyalty_number
                    Minimum: 10
                    Type: COUNT_DISTINCT
                ScalarFunctions: []
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
