---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - city
        - clv
        - country
        - education
        - enrollment_month
        - enrollment_type
        - enrollment_year
        - gender
        - loyalty_card
        - marital_status
        - salary
        - postal_code
        - province
        - loyalty_number
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: AGGREGATION
          Policy:
            V1:
              Aggregation:
                AggregateColumns:
                  - Function: AVG
                    ColumnNames:
                    - salary
                    - clv
                DimensionColumns:
                  - city
                  - country
                  - education
                  - enrollment_month
                  - enrollment_type
                  - enrollment_year
                  - gender
                  - loyalty_card
                  - marital_status
                  - postal_code
                  - province
                JoinColumns:
                  - loyalty_number
                JoinRequired: QUERY_RUNNER
                OutputConstraints:
                  - ColumnName: loyalty_number
                    Minimum: 10
                    Type: COUNT_DISTINCT
                ScalarFunctions: []
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
