---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - distance
        - dollar cost points redeemed
        - flights booked
        - flights with companions
        - loyalty number
        - month
        - points accumulated
        - points redeemed
        - total flights
        - year
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: AGGREGATION
          Policy:
            V1:
              Aggregation:
                AggregateColumns:
                  - Function: AVG
                    ColumnNames:
                    - points accumulated
                    - points redeemed
                  - Function: SUM
                    ColumnNames:
                    - points accumulated
                    - points redeemed
                  - Function: COUNT_DISTINCT
                    ColumnNames:
                    - loyalty number
                DimensionColumns:
                  - distance
                  - dollar cost points redeemed
                  - flights booked
                  - flights with companions
                  - month
                  - total flights
                  - year
                JoinColumns:
                  - loyalty number
                JoinRequired: QUERY_RUNNER
                OutputConstraints:
                  - ColumnName: loyalty number
                    Minimum: 10
                    Type: COUNT_DISTINCT
                ScalarFunctions: []
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
