---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - city
        - clv
        - country
        - education
        - enrollment month
        - enrollment type
        - enrollment year
        - gender
        - loyalty card
        - marital status
        - salary
        - postal code
        - province
        - loyalty number
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: AGGREGATION
          Policy:
            V1:
              Aggregation:
                AggregateColumns:
                  - Function: COUNT_DISTINCT
                    ColumnNames:
                    - loyalty number
                DimensionColumns:
                  - city
                  - clv
                  - country
                  - education
                  - enrollment month
                  - enrollment type
                  - enrollment year
                  - gender
                  - loyalty card
                  - marital status
                  - salary
                  - postal code
                  - province
                JoinColumns: []
                OutputConstraints:
                  - ColumnName: loyalty number
                    Minimum: 100
                    Type: COUNT_DISTINCT
                ScalarFunctions: []
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
