---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - distance
        - dollar_cost_points_redeemed
        - flights_booked
        - flights_with_companions
        - loyalty_number
        - month
        - points_accumulated
        - points_redeemed
        - total_flights
        - year
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: LIST
          Policy:
            V1:
              List:
                AllowedJoinOperators: []
                JoinColumns:
                  - loyalty_number
                ListColumns:
                  - distance
                  - dollar_cost_points_redeemed
                  - flights_booked
                  - flights_with_companions
                  - month
                  - points_accumulated
                  - points_redeemed
                  - total_flights
                  - year
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
