---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - city
        - clv
        - country
        - education
        - enrollment month
        - enrollment type
        - enrollment year
        - gender
        - loyalty card
        - marital status
        - postal code
        - province
        - salary
        - loyalty number
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: LIST
          Policy:
            V1:
              List:
                AllowedJoinOperators: []
                JoinColumns:
                  - loyalty number
                ListColumns:
                  - city
                  - clv
                  - country
                  - education
                  - enrollment month
                  - enrollment type
                  - enrollment year
                  - gender
                  - loyalty card
                  - marital status
                  - postal code
                  - province
                  - salary
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
