---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
  GlueDatabaseName:
    Type: String
  GlueTableName:
    Type: String
Resources:
  ConfiguredTable:
    Type: AWS::CleanRooms::ConfiguredTable
    Properties:
      Name: !Ref TableName
      AnalysisMethod: DIRECT_QUERY
      AllowedColumns:
        - city
        - country
        - enrollment_month
        - enrollment_type
        - enrollment_year
        - gender
        - loyalty_card
        - province
        - loyalty_number
      TableReference:
        Glue:
          DatabaseName: !Ref GlueDatabaseName
          TableName: !Ref GlueTableName
      AnalysisRules:
        - Type: LIST
          Policy:
            V1:
              List:
                AllowedJoinOperators: []
                JoinColumns:
                  - loyalty_number
                ListColumns:
                  - city
                  - country
                  - enrollment_month
                  - enrollment_type
                  - enrollment_year
                  - gender
                  - loyalty_card
                  - province
Outputs:
  ConfiguredTableId:
    Value: !GetAtt ConfiguredTable.ConfiguredTableIdentifier
